image: registry.gitlab.com/showcheap/android-ci:T25-B25.0.3

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
     - .gradle/
  key: "$CI_COMMIT_REF_NAME"

build:
  stage: build
  script:
    - ./gradlew --no-daemon --stacktrace assembleDebug
    - mv app/build/outputs/apk/app-debug.apk .
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}-${CI_BUILD_ID}"
    paths:
    - app-debug.apk

tests:
  stage: test
  script:
    - ./gradlew --no-daemon --stacktrace test
    - ./gradlew --no-daemon --stacktrace check
  artifacts:
    paths:
    - app/build/reports
