image: circleci/android:api-25-alpha

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle
     - gradle-3.3

before_script:
    - export GRADLE_USER_HOME=`pwd`/gradle-3.3

build:
  stage: build
  script:
    - sudo rm -rf .gradle gradle-3.3
    - ./gradlew --no-daemon --stacktrace dependencies || true
    - ./gradlew --no-daemon --stacktrace assembleDebug
    - mv app/build/outputs/apk/app-debug.apk .
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}-${CI_BUILD_ID}"
    paths:
    - app-debug.apk

tests:
  stage: test
  script:
    - ./gradlew --no-daemon --stacktrace test
  artifacts:
    paths:
    - app/build/reports/tests

lint:
  stage: test
  script:
    - ./gradlew --no-daemon --stacktrace lint
  artifacts:
    paths:
    - app/build/reports
