coverage:
  range: 60..100
  status:
    project:
      default: off
      api:
        target: 80%
        flags: api
      app:
        target: 20%
        flags: app
      instrumented:
        target: 20%
        flags: instrumented

flags:
  api:
    paths:
      - api/src/main/io/github/wulkanowy
  app:
    paths:
      - app/src/main/io/github/wulkanowy
  instrumented:
    paths:
      - app/src/main/io/github/wulkanowy
